name = "bams-chat-of-the-day"
compatibility_date = "2024-01-01"

[assets]
directory = "./dist"

[[routes]]
pattern = "ilyambr.com/bams/chat*"
zone_name = "ilyambr.com"

[[routes]]
pattern = "www.ilyambr.com/bams/chat*"
zone_name = "ilyambr.com"
